import { PageShell } from "../components/Shell";
import Icon from "../components/Icon";
import { Card, CTA, FAQ, SectionIntro } from "../components/Blocks";
import ContactForm from "../components/ContactForm";
import { analysisPhases, benefits, businessCards, deliverables, faqs, notVisit, process, problemCards, upcomingZones, whyNow, yesVisit } from "../../src/data/presentialAuditPage";

export const metadata = {
  title: "Mystery Guest customer experience audit | Kaiori",
  description: "Mystery Guest customer experience audit for hotels, accommodation, restaurants, tours and experiences. Kaiori analyses your business as a real guest and detects actionable improvements.",
  alternates: {
    canonical: "/mystery-guest",
  },
};

export default function AuditoriaPresencialPage() {
  return (
    <PageShell>
      <main>
        <section className="hero"><div className="container hero-grid"><div><p className="eyebrow">Mystery Guest</p><h1>We analyse your business from within, as real guests.</h1><p className="lead">We visit your accommodation, restaurant, tour or experience to observe arrival, service, cleanliness, timing, communication, expectations and final perception.</p><p>We live the service with an external eye and turn findings into concrete improvements.</p><div className="hero-actions"><a className="btn btn-primary" href="#diagnosis-form">Request a Mystery Guest audit <Icon name="arrowRight" className="icon-sm" /></a><a className="btn btn-secondary" href="#what-we-audit">See what we audit</a></div></div><div className="hero-card">{["Booking", "Arrival", "Experience", "Departure", "Review"].map((x, i) => <div className="journey-row" key={x}><span className="number">0{i + 1}</span>{x}</div>)}<p>We observe what the guest perceives, not only what the business believes it offers.</p></div></div></section>
        <section id="zones" className="section white"><div className="container"><SectionIntro eyebrow="Upcoming audit areas" title="We will soon be analysing experiences in Oceania and the Pacific." text="During our next work route, we will carry out Mystery Guest audits in selected destinations across Australia, New Zealand, Oceania, Pacific Islands and French Polynesia." /><div className="grid grid-3">{upcomingZones.map(([t, x]) => <Card key={t} icon="mapPin" title={t} text={x} />)}</div><a className="btn btn-primary" href="#diagnosis-form">Check availability</a></div></section>
        <section className="section surface"><div className="container"><SectionIntro eyebrow="The problem" title="The real experience does not always match what the business believes it offers." text="A business can have good photos, a correct website and positive reviews, yet still accumulate small details that only appear when someone lives the full experience." /><div className="grid grid-4">{problemCards.map(([t, x, i]) => <Card key={t} icon={i} title={t} text={x} />)}</div></div></section>
        <section className="section white"><div className="container hero-grid"><div><SectionIntro eyebrow="What it is" title="What a Kaiori Mystery Guest audit is" text="Mystery Guest is an analysis of the real customer experience from within. Kaiori visits the business, lives the service as a guest would and evaluates each phase of the journey with an analytical, business-focused view." /><p className="card">Where the business sees routine, the guest perceives details.</p></div><div className="grid grid-2">{["Real visit to the business.", "Evaluation from the guest's perspective.", "Complete experience analysis.", "Detection of on-site friction.", "Comparison between expectation and reality.", "Actionable recommendations.", "Practical, not theoretical approach.", "Business improvement focus."].map((x) => <Card key={x} icon="checkCircle" text={x} />)}</div></div></section>
        <section className="section surface"><div className="container"><SectionIntro eyebrow="Who it is for" title="What type of businesses it is designed for" text="Mystery Guest is designed for businesses where the lived experience directly affects booking, satisfaction, reputation and recommendation." /><div className="grid grid-3">{businessCards.map((b) => <Card key={b.title} icon={b.icon} title={b.title} text={b.text}><ul>{b.items.map((x) => <li key={x}><Icon name="checkCircle" className="icon-sm" />{x}</li>)}</ul><a className="btn btn-secondary" href="#diagnosis-form">{b.cta}</a></Card>)}</div></div></section>
        <section id="what-we-audit" className="section white"><div className="container"><SectionIntro eyebrow="What we audit" title="What we analyse during the visit" text="We observe every point of the real customer journey, from what guests expect before arriving to what they remember afterwards." /><div className="grid grid-3">{analysisPhases.map((p) => <Card key={p.title} icon={p.icon} title={p.title} text={p.text}><ul>{p.items.map((x) => <li key={x}>{x}</li>)}</ul></Card>)}</div></div></section>
        <section id="deliverables" className="section surface"><div className="container"><SectionIntro eyebrow="What you receive" title="What the business receives after the audit" text="We do not deliver a subjective opinion. We deliver a clear, structured analysis focused on improvement." /><div className="grid grid-3">{deliverables.map(([t, x, i]) => <Card key={t} icon={i} title={t} text={x} />)}</div></div></section>
        <section className="section white"><div className="container"><SectionIntro eyebrow="What it is not" title="It is not a promotional visit. It is real experience analysis." /><div className="grid grid-2"><Card title="It is not"><ul>{notVisit.map((x) => <li key={x}><Icon name="x" className="icon-sm icon-danger" />{x}</li>)}</ul></Card><Card className="dark" title="It is"><ul>{yesVisit.map((x) => <li key={x}><Icon name="checkCircle" className="icon-sm" />{x}</li>)}</ul></Card></div></div></section>
        <section className="section surface"><div className="container"><SectionIntro eyebrow="Why now" title="Why request Mystery Guest during our next route" text="Mystery Guest audits require planning, travel and geographical fit." /><div className="grid grid-4">{whyNow.map(([t, x, i]) => <Card key={t} icon={i} title={t} text={x} />)}</div></div></section>
        <section id="process" className="section white"><div className="container"><SectionIntro eyebrow="Process" title="How Mystery Guest works" /><div className="grid grid-3">{process.map(([t, x], i) => <Card key={t} title={`0${i + 1}. ${t}`} text={x} />)}</div></div></section>
        <section className="section surface"><div className="container"><SectionIntro eyebrow="Benefits" title="What it can bring to your business" /><div className="grid grid-3">{benefits.map(([t, x, i]) => <Card key={t} icon={i} title={t} text={x} />)}</div></div></section>
        <CTA title="Does Mystery Guest make sense for your business?" text="Tell us where your business is and we will review whether it fits the next route." href="#diagnosis-form" label="Check Mystery Guest availability" />
        <section id="faq" className="section white"><div className="container"><SectionIntro center eyebrow="FAQ" title="Frequently asked questions about Mystery Guest" /><FAQ items={faqs} /></div></section>
        <ContactForm eyebrow="Mystery Guest" title="Request a Mystery Guest audit" subtitle="Tell us where your business is and we will review whether it can fit into our next route." intro="We will assess location, experience type and scope before proposing the next step." defaultService="mystery-guest" sourcePage="mystery-guest" submitButtonText="Send request" locationLabel="Business location *" locationPlaceholder="E.g. Sydney, Australia / Auckland, New Zealand / Bora Bora, French Polynesia" locationHelp="Tell us the city, island or area so we can assess whether it fits our route." />
      </main>
    </PageShell>
  );
}
